### ISSUE TITLE
Add scan_interval to the scrape documentation

### ISSUE THREAD

**Issue by mickecamino** [henricm/ha-ferroamp#345]
I did notice that there are a new section in the documentation for checking if Ferroamp releases a new firmware version. That is great.
But.....
Default for the scrape function is to poll every 10:th minute and that is way abusive as the release rate of Ferroamp is quite low.
Add scan_interval with the value of 86400 so that polling is done once a day, or once a week with 604800.

```
scrape:
  - resource: https://support.ferroamp.com/sv-SE/support/solutions/47000522529
    timeout: 10
    scan_interval: 86400
    sensor:
      - name: Ferroamp Latest Version
        select: '.file-card > .fw-no-bullet > li'
        icon: mdi:counter
        index: 0
        value_template: >

```
