### ISSUE TITLE
Question: How to keep history for external voltage for each phase?

### ISSUE THREAD

**Issue by bj00rn** [henricm/ha-ferroamp#353]
Wouldn't it be nice to have a a separate sensor for external voltage for each phase for history purposes?

Correct me if i'm wrong, In the current implementation, per phase values are implemented as state attributes and are not recorded.

Phase history is helpful when trying to understand if SSO/EH fault codes are related to grid voltage.

Im using a workaround is to create a template sensor to grab phase voltage..

**Comment by henricm** [comment]
I've also thought about this actually. I think it's a good idea to extract the values for each phase to be sensors of their own. Or are there other attributes too? I'm thinking about the sensors that have L1, L2, L3 attributes.

**Comment by argoyle** [comment]
There is a pos/neg somewhere and probably something else but most are L1, L2, L3. I'll see if I can find the time to do something.

**Comment by bj00rn** [comment]
> There is a pos/neg somewhere and probably something else but most are L1, L2, L3. I'll see if I can find the time to do something.

For diagnostics it would be a nice feature. I guess downside is there will be a lot of sensors 🤓 . 

- `external_voltage` => `external_voltage_l1`, `external_voltage_l2`, `external_voltage_l3`
- `grid_current` => `grid_current_l1`, `grid_current_l2`, `grid_current_l3`
- `external_reactive_current` =>  `external_reactive_current_l1`,`external_reactive_current_l2`,`external_reactive_current_l3` 
- etc..

Maybe it's a good idea to keep the original the original sensors too. For sensors like `grid_power` I guess the general use case is looking at all phases combined rather than individual phases.

**Comment by robinostlund** [comment]
Think also this feature would be good, i have solved this today by creating templates:

```
---
sensor:
  - name: "Ferroamp Adaptive Current Equalization Phase 1"
    unique_id: "ferroamp_adaptive_current_equalization_phase_1"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {{ state_attr('sensor.ferroamp_adaptive_current_equalization','L1') }}

  - name: "Ferroamp Adaptive Current Equalization Phase 2"
    unique_id: "ferroamp_adaptive_current_equalization_phase_2"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {{ state_attr('sensor.ferroamp_adaptive_current_equalization','L2') }}

  - name: "Ferroamp Adaptive Current Equalization Phase 3"
    unique_id: "ferroamp_adaptive_current_equalization_phase_3"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {{ state_attr('sensor.ferroamp_adaptive_current_equalization','L3') }}

  - name: "Ferroamp Grid Main Fuse"
    unique_id: "ferroamp_grid_main_fuse"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state: 16

  - name: "Ferroamp Grid Power Max"
    unique_id: "ferroamp_grid_power_max"
    device_class: power
    icon: "mdi:transmission-tower"
    unit_of_measurement: W
    state: >
      {% set grid_main_fuse = int(states('sensor.ferroamp_grid_main_fuse'), 16) %}
      {% set grid_max_power = grid_main_fuse * 3 * 230 %}
      {{ grid_max_power }}

  - name: "Ferroamp Grid Power Available"
    unique_id: "ferroamp_grid_power_available"
    device_class: power
    icon: "mdi:transmission-tower"
    unit_of_measurement: W
    state_class: measurement
    state: >
      {% set grid_max_power = int(states('sensor.ferroamp_grid_power_max'), 0) %}
      {% set grid_current_power = int(states('sensor.ferroamp_grid_power'), 0) %}

      {% set power = 0 %}
      {% if grid_current_power < 0 %}
        {% set power = int(grid_max_power + (grid_current_power * -1), 0) %}
      {% else %}
        {% set power = int(grid_max_power - grid_current_power, 0) %}
      {% endif %}

      {{ power }}

  - name: "Ferroamp Grid Current Available"
    unique_id: "ferroamp_grid_current_available"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {% set grid_power_available = int(states('sensor.ferroamp_grid_power_available'), 0) %}
      {% set current = int(grid_power_available / 230, 0) %}
      {{ current }}

  - name: "Ferroamp Grid Current Phase 1"
    unique_id: "ferroamp_grid_current_phase_1"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {{ state_attr('sensor.ferroamp_grid_current','L1') }}

  - name: "Ferroamp Grid Power Phase 1"
    unique_id: "ferroamp_grid_power_phase_1"
    device_class: power
    icon: "mdi:power-plug"
    unit_of_measurement: W
    state_class: measurement
    state: >
      {% set power = int(state_attr('sensor.ferroamp_grid_power','L1'), 0) %}
      {{ power }}

  - name: "Ferroamp Grid Current Phase 2"
    unique_id: "ferroamp_grid_current_phase_2"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {{ state_attr('sensor.ferroamp_grid_current','L2') }}

  - name: "Ferroamp Grid Power Phase 2"
    unique_id: "ferroamp_grid_power_phase_2"
    device_class: power
    icon: "mdi:power-plug"
    unit_of_measurement: W
    state_class: measurement
    state: >
      {% set power = int(state_attr('sensor.ferroamp_grid_power','L2'), 0) %}
      {{ power }}


  - name: "Ferroamp Grid Current Phase 3"
    unique_id: "ferroamp_grid_current_phase_3"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {{ state_attr('sensor.ferroamp_grid_current','L3') }}


  - name: "Ferroamp Grid Power Phase 3"
    unique_id: "ferroamp_grid_power_phase_3"
    device_class: power
    icon: "mdi:power-plug"
    unit_of_measurement: W
    state_class: measurement
    state: >
      {% set power = int(state_attr('sensor.ferroamp_grid_power','L3'), 0) %}
      {{ power }}


  - name: "Ferroamp Consumption Current Phase 1"
    unique_id: "ferroamp_consumption_current_phase_1"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {% set power = int(states('sensor.ferroamp_consumption_power_phase_1'), 0) %}
      {% set current = float(power / 230, 0) %}
      {% if current < 0 %}
        {% set current = 0 %}
      {% endif %}
      {{ current | round(2) }}

  - name: "Ferroamp Consumption Power Phase 1"
    unique_id: "ferroamp_consumption_power_phase_1"
    device_class: power
    icon: "mdi:power-plug"
    unit_of_measurement: W
    state_class: measurement
    state: >
      {% set power = int(state_attr('sensor.ferroamp_consumption_power','L1'), 0) %}
      {{ power }}


  - name: "Ferroamp Consumption Current Phase 2"
    unique_id: "ferroamp_consumption_current_phase_2"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {% set power = int(states('sensor.ferroamp_consumption_power_phase_2'), 0) %}
      {% set current = float(power / 230, 0) %}
      {% if current < 0 %}
        {% set current = 0 %}
      {% endif %}
      {{ current | round(2) }}

  - name: "Ferroamp Consumption Power Phase 2"
    unique_id: "ferroamp_consumption_power_phase_2"
    device_class: power
    icon: "mdi:power-plug"
    unit_of_measurement: W
    state_class: measurement
    state: >
      {% set power = int(state_attr('sensor.ferroamp_consumption_power','L2'), 0) %}
      {{ power }}


  - name: "Ferroamp Consumption Current Phase 3"
    unique_id: "ferroamp_consumption_current_phase_3"
    device_class: current
    icon: "mdi:current-ac"
    unit_of_measurement: A
    state_class: measurement
    state: >
      {% set power = int(states('sensor.ferroamp_consumption_power_phase_3'), 0) %}
      {% set current = float(power / 230, 0) %}
      {% if current < 0 %}
        {% set current = 0 %}
      {% endif %}
      {{ current | round(2) }}

  - name: "Ferroamp Consumption Power Phase 3"
    unique_id: "ferroamp_consumption_power_phase_3"
    device_class: power
    icon: "mdi:power-plug"
    unit_of_measurement: W
    state_class: measurement
    state: >
      {% set power = int(state_attr('sensor.ferroamp_consumption_power','L3'), 0) %}
      {{ power }}
```
