### ISSUE TITLE
No history for SSO Relay Status in history-graph

### ISSUE THREAD

**Issue by bj00rn** [henricm/ha-ferroamp#92]
Thanks for a great integration, works like a charm!

I would like to show a history-graphs ideally a bars for various state sensors but i can't get it to work properly.

I've been mucking around with SSO Relay Status (and SSO Fault Code) with configurations like below.

Seems there is no state history for this sensor, is this expected behaviour?

Am I missing something? Im pretty new to HA.

```yaml
type: history-graph
entities:
  - entity: sensor.energyhub_14_sso_21020540_relay_status
  - entity: sensor.energyhub_14_sso_21020540_relay_status
  - entity: sensor.energyhub_14_sso_21030452_relay_status
  - entity: sensor.energyhub_14_sso_21030613_relay_status
hours_to_show: 24000
refresh_interval: 1
```

![image](https://user-images.githubusercontent.com/10961167/142774912-8199c16f-4f70-4297-b822-4b738a68b340.png)

Thanks again!
